name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: vivekchinchole/crud-app
  K8S_NAMESPACE: default

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build & Test
        run: mvn clean package

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Image
        run: |
          docker build -t $DOCKER_IMAGE:latest .
          docker push $DOCKER_IMAGE:latest

  deploy-to-k8s:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/postgres.yaml
          kubectl apply -f k8s/deployment.yaml


#name: CI/CD Pipeline
#
#on:
#  push:
#    branches: [ main, develop ]
#  pull_request:
#    branches: [ main ]
#
#env:
#  DOCKER_IMAGE: vivekchinchole/crud-app
#  K8S_NAMESPACE: default
#
#jobs:
#  build-and-test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build with Maven
#        run: mvn clean install
#
#      - name: Run tests
#        run: mvn test
#
#      - name: Generate test report
#        if: always()
#        run: mvn surefire-report:report
#
#      - name: Upload test results
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-results
#          path: target/surefire-reports/
#
#  docker-build-push:
#    needs: build-and-test
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Extract metadata
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: ${{ env.DOCKER_IMAGE }}
#          tags: |
#            type=sha,prefix={{branch}}-
#            type=raw,value=latest
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#
#  deploy-to-k8s:
#    needs: docker-build-push
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Configure kubectl
#        uses: azure/k8s-set-context@v3
#        with:
#          method: kubeconfig
#          kubeconfig: ${{ secrets.KUBE_CONFIG }}
#
#      - name: Deploy ConfigMap
#        run: |
#          kubectl apply -f k8s/configmap.yaml -n ${{ env.K8S_NAMESPACE }}
#
#      - name: Deploy Secret
#        run: |
#          kubectl apply -f k8s/secret.yaml -n ${{ env.K8S_NAMESPACE }}
#
#      - name: Deploy PostgreSQL
#        run: |
#          kubectl apply -f k8s/postgres.yaml -n ${{ env.K8S_NAMESPACE }}
#
#      - name: Wait for PostgreSQL
#        run: |
#          kubectl wait --for=condition=ready pod -l app=postgres -n ${{ env.K8S_NAMESPACE }} --timeout=300s
#
#      - name: Deploy Application
#        run: |
#          kubectl apply -f k8s/deployment.yaml -n ${{ env.K8S_NAMESPACE }}
#
#      - name: Wait for deployment
#        run: |
#          kubectl rollout status deployment/crud-app-deployment -n ${{ env.K8S_NAMESPACE }} --timeout=300s
#
#      - name: Get service URL
#        run: |
#          kubectl get service crud-app-service -n ${{ env.K8S_NAMESPACE }}